name: firecracker-containerd
on:
  push:
    branches:
      - main
jobs:
  firecracker-containerd:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: brew install ansible
      - run: vagrant up
