---
- name: firecracker-containerd
  hosts: all
  tasks:
    - name: Install required dependencies
      ansible.builtin.shell: /bin/sh /vagrant/ansible-playbooks/scripts/install-required-dependencies.sh
    - name: Reset SSH connection
      meta: reset_connection
    - name: Install firecracker-containerd
      ansible.builtin.shell: |
        source ~/.bashrc
        /bin/sh /vagrant/ansible-playbooks/scripts/install-firecracker-containerd.sh
    - name: Start firecracker-containerd
      ansible.builtin.shell: firecracker-containerd --config /etc/firecracker-containerd/config.toml
